<?php 
return [
    'invoice-name'         => 'PerfectMoney',
    'option-name'          => 'PerfectMoney',
    'name'                 => 'PerfectMoney',
    'redirect-message'     => 'Redirecting to PerfectMoney...',
    'description'          => '',
    'id'                   => 'Account ID',
    'password'             => 'Alternate Password',
    'currency'             => 'Your PerfectMoney Currency',
    'id-desc'              => 'e.g: U12345678',
    'password-desc'        => 'Alternate Password can be generated by going to settings page and press the "Generate" button in the "Alternate Passphrase" field',
    'currency-desc'        => ' ',
    'commission-rate'      => 'Commission Rate (%)',
    'commission-rate-desc' => 'Enter the percentage (%) value for commission fees',
    'save-button'          => 'Save Settings',
    'success1'             => 'Settings saved successfully',
];
