<?php
    return [
        'type' => "hosting",
        'server-info-checker' => true,
        'server-info-port' => true,
        'server-info-not-secure-port' => 2086,
        'server-info-secure-port' => 2087,
        'default-aclist' => [
            'acl-edit-pkg' => 1,
            'acl-add-pkg' => 1,
            'acl-list-pkgs' => 1,
            'acl-list-users' => 1,
            'acl-ssl' => 1,
            'acl-ssl-buy' => 1,
            'acl-mailcheck' => 1,
            'acl-show-bandwidth' => 1,
            'acl-list-accts' => 1,
            'acl-acct-summary' => 1,
            'acl-kill-dns' => 1,
            'acl-edit-dns' => 1,
            'acl-park-dns' => 1,
            'acl-create-dns' => 1,
            'acl-create-acct' => 1,
            'acl-suspend-acct' => 1,
            'acl-basic-system-info' => 1,
            'acl-passwd' => 1,
            'acl-upgrade-account' => 1,
            'acl-ssl-gencrt' => 1,
            'acl-edit-mx' => 1,
            'acl-kill-acct' => 1,
            'acl-allow-addoncreate' => 1,
            'acl-allow-parkedcreate' => 1,
            'acl-thirdparty' => 1,
            'acl-news' => 1,
            'acl-add-pkg-ip' => 1,
            'acl-add-pkg-shell' => 1,
            'acl-allow-unlimited-pkgs' => 1,
            'acl-allow-emaillimits-pkgs' => 1,
            'acl-allow-unlimited-disk-pkgs' => 1,
            'acl-allow-unlimited-bw-pkgs' => 1,
        ],
        'supported' => [
            'disk-bandwidth-usage',
            'manage-email-account',
            'manage-email-forwards',
            'change-password',
        ],
    ];