<?php
    return [
        'type'                          => "virtualization",
        'access-hash'                   => false,
        'server-info-checker'           => true,
        'server-info-port'              => false,
        'server-info-not-secure-port'   => 80,
        'server-info-secure-port'       => 80,
        'configurable-option-params'    => [
            'params_name',
            'server_name',
            'memory',
            'swap',
            'io',
            'cpu',
            'disk',
            'nest_id',
            'egg_id',
            'pack_id',
            'location_id',
            'dedicated_ip',
            'port_range',
            'image',
            'startup',
            'databases',
            'allocations',
            'backups',
            'oom_disabled',
            'username',
        ],
    ];