<?php
    return [
        'type' => "virtualization",
        'server-info-checker' => true,
        'server-info-port' => true,
        'server-info-not-secure-port' => 4084,
        'server-info-secure-port' => 4085,
        'types' => [
            'OpenVZ'                => 'openvz',
            'Xen PV'                => 'xen',
            'Xen HVM'               => 'xen',
            'KVM'                   => 'kvm',
            'XCP HVM'               => 'xcp',
            'XCP PV'                => 'xcp',
            'LXC'                   => 'lxc',
            'Virtuozzo OpenVZ'      => 'vzo',
            'Virtuozzo KVM'         => 'vzk',
            'Proxmox KVM'           => 'proxk',
            'Proxmox OpenVZ'        => 'proxo',
            'Proxmox LXC'           => 'proxl',
        ],
        'configurable-option-params' => [
            'Number of IPs',
            'Number of IPv6 Address',
            'Number of IPv6 Subnet',
            'Number of Internal IP Address',
            'Space',
            'RAM',
            'Bandwidth',
            'CPU Cores',
            'Network Speed',
            'CPU Percent',
            'Operating System',
            'Control Panel',
            'Managed by Admin',
            'Server',
            'Region',
            'hostname',
            'swapram',
            'virtio',
            'nic_type',
            'vif_type',
            'osreinstall_limit',
            'kvm_cache',
            'io_mode',
            'iso',
            'sec_iso',
            'mgs',
            'stid',
            'ippoolid',
            'dnsplid',
            'Total I/Os per sec',
            'Read Mega Bytes/s',
            'Write Mega Bytes/s',
            'topology_sockets',
            'topology_cores',
            'topology_threads',
            'rdp',
            'bpid',
            'upload_speed',
            'recipe',
            'ha',
        ],
    ];