<?php 
return [
    'notifications' => [
        'invoice'        => [
            'invoice-created'               => [
                'variables'   => '{invoice_id},{invoice_num},{invoice_payment_link},{invoice_items},{invoice_items_html},{invoice_subtotal},{invoice_total},{invoice_tax_rate},{invoice_tax},{invoice_date_created},{invoice_date_due}',
                'emails'      => '',
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'invoice-returned'              => [
                'variables'   => '{invoice_id},{invoice_num},{invoice_payment_link},{invoice_items},{invoice_items_html},{invoice_subtotal},{invoice_total},{invoice_tax_rate},{invoice_tax},{invoice_date_created},{invoice_date_due},{invoice_refund_date}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'invoice-cancelled'             => [
                'variables'   => '{invoice_id},{invoice_num},{invoice_payment_link},{invoice_items},{invoice_items_html},{invoice_subtotal},{invoice_total},{invoice_tax_rate},{invoice_tax},{invoice_date_created},{invoice_date_due},{invoice_cancelled_date}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'invoice-reminder'              => [
                'variables'   => '{invoice_id},{invoice_num},{invoice_payment_link},{invoice_items},{invoice_items_html},{invoice_subtotal},{invoice_total},{invoice_tax_rate},{invoice_tax},{invoice_date_created},{invoice_date_due},{invoice_remaining_day}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'invoice-overdue'               => [
                'variables'   => '{invoice_id},{invoice_num},{invoice_payment_link},{invoice_items},{invoice_items_html},{invoice_subtotal},{invoice_total},{invoice_tax_rate},{invoice_tax},{invoice_date_created},{invoice_date_due}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'invoice-has-been-approved'     => [
                'variables'   => '{invoice_id},{invoice_num},{invoice_payment_link},{invoice_items},{invoice_items_html},{invoice_subtotal},{invoice_total},{invoice_tax_rate},{invoice_tax},{invoice_date_created},{invoice_date_due},{invoice_payment_method},{invoice_date_paid}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'invoice-has-been-taxed'        => [
                'variables'   => '{invoice_id},{invoice_num},{invoice_payment_link},{invoice_items},{invoice_items_html},{invoice_subtotal},{invoice_total},{invoice_tax_rate},{invoice_tax},{invoice_date_created},{invoice_date_due},{invoice_date_taxed},{legal_invoice_download_link}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'invoice-awaiting-confirmation' => [
                'variables'   => '{invoice_id},{invoice_num},{invoice_payment_link},{invoice_items},{invoice_items_html},{invoice_subtotal},{invoice_total},{invoice_tax_rate},{invoice_tax},{invoice_date_created},{invoice_date_due},{invoice_payment_method},{invoice_date_paid}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'invoice-auto-payment-failed'   => [
                'variables'   => '{invoice_id},{invoice_num},{invoice_payment_link},{invoice_items},{invoice_items_html},{invoice_subtotal},{invoice_total},{invoice_tax_rate},{invoice_tax},{invoice_date_created},{invoice_date_due},{invoice_remaining_day},{error_message},{card_ln4}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => [],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'invoice-subscription-payment-failed'   => [
                'variables'   => '{module},{total}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => [],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
        ],
        'order'          => [
            'order-has-been-taken'      => [
                'variables'   => '{order_items},{order_items_html},{order_subtotal},{order_total},{order_tax_rate},{order_tax},{order_date_created},{invoice_payment_method}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'order-has-been-approved'   => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_date_approved},{order_detail_link}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'order-has-been-suspended'  => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'order-has-been-activated'  => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'order-has-been-cancelled'  => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'hosting-server-activation' => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link},{order_infos_html},{order_infos_text}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'order-has-been-extended'   => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
        ],
        'domain'         => [
            'domain-registered'           => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link},{domain}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'domain-transfered'           => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link},{domain}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'domain-has-been-activated'   => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link},{domain}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'domain-has-been-extended'    => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link},{domain}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'domain-has-been-suspended'   => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link},{domain}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'domain-has-been-cancelled'   => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link},{domain}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'domain-submit-transfer-code' => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link},{domain},{domain_transfer_code}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
        ],
        'sms'            => [
            'sms-origin-request-received'     => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{origin_detail_link},{origin_name}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 1,
            ],
            'sms-origin-has-been-approved'    => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{origin_detail_link},{origin_name}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'sms-origin-has-been-inactivated' => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{origin_detail_link},{origin_name},{reason}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
        ],
        'sms-intl'       => [
            'sms-intl-origin-request-received'     => [
                'variables'   => '{origin_name},{origin_detail_link},{country}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 1,
            ],
            'sms-intl-origin-has-been-approved'    => [
                'variables'   => '{origin_name},{origin_detail_link},{country}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => [],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'sms-intl-origin-has-been-inactivated' => [
                'variables'   => '{origin_detail_link},{origin_name},{reason},{country}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => [],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
        ],
        'user-tickets'   => [
            'ticket-resolved-automatic'        => [
                'variables'   => '{ticket_id},{ticket_link},{ticket_subject},{user_last_message},{admin_last_message},{ticket_department},{ticket_service},{ticket_status},{ticket_priority},{ticket_admin_name}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'ticket-replied-by-admin'          => [
                'variables'   => '{ticket_id},{ticket_link},{ticket_subject},{user_last_message},{admin_last_message},{ticket_department},{ticket_service},{ticket_status},{ticket_priority},{ticket_admin_name}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'ticket-has-been-created-by-admin' => [
                'variables'   => '{ticket_id},{ticket_link},{ticket_subject},{user_last_message},{admin_last_message},{ticket_department},{ticket_service},{ticket_status},{ticket_priority},{ticket_admin_name}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => false,
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'ticket-your-has-been-created'     => [
                'variables'   => '{ticket_id},{ticket_link},{ticket_subject},{user_last_message},{admin_last_message},{ticket_department},{ticket_service},{ticket_status},{ticket_priority},{ticket_admin_name}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'ticket-your-has-been-processed'   => [
                'variables'   => '{ticket_id},{ticket_link},{ticket_subject},{user_last_message},{admin_last_message},{ticket_department},{ticket_service},{ticket_status},{ticket_priority},{ticket_admin_name}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'ticket-resolved-by-admin'         => [
                'variables'   => '{ticket_id},{ticket_link},{ticket_subject},{user_last_message},{admin_last_message},{ticket_department},{ticket_service},{ticket_status},{ticket_priority},{ticket_admin_name}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
        ],
        'admin-tickets'  => [
            'ticket-assigned-to-you'          => [
                'variables'   => '{ticket_id},{ticket_link},{ticket_subject},{user_last_message},{admin_last_message},{ticket_department},{ticket_service},{ticket_status},{ticket_priority},{ticket_admin_name},{ticket_assigned_by_admin}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => false,
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 1,
            ],
            'ticket-resolved-by-user'         => [
                'variables'   => '{ticket_id},{ticket_link},{ticket_subject},{user_last_message},{admin_last_message},{ticket_department},{ticket_service},{ticket_status},{ticket_priority},{ticket_admin_name}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 1,
            ],
            'ticket-replied-by-user'          => [
                'variables'   => '{ticket_id},{ticket_link},{ticket_subject},{user_last_message},{admin_last_message},{ticket_department},{ticket_service},{ticket_status},{ticket_priority},{ticket_admin_name}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 1,
            ],
            'ticket-has-been-created-by-user' => [
                'variables'   => '{ticket_id},{ticket_link},{ticket_subject},{user_last_message},{admin_last_message},{ticket_department},{ticket_service},{ticket_status},{ticket_priority},{ticket_admin_name}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 1,
            ],
        ],
        'user'           => [
            'welcome'                       => [
                'variables'   => '',
                'emails'      => NULL,
                'phones'      => '',
                'departments' => [],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'forget-password'               => [
                'variables'   => '{verify_link}',
                'emails'      => NULL,
                'phones'      => '',
                'departments' => false,
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'forget-password-admin'         => [
                'variables'   => '{verify_link}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => false,
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'email-activation'              => [
                'variables'   => '{activation_code},{activation_link}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => false,
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'gsm-activation'                => [
                'variables'   => '{activation_code}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => false,
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'approve-ctoc-service-transfer' => [
                'variables'   => '{product_name},{order_id},{order_name},{order_amount},{from_id},{from_full_name},{from_email},{to_id},{to_full_name},{to_email},{approve_link}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => false,
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'account-has-been-blocked'      => [
                'variables'   => '',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'account-has-been-activated'    => [
                'variables'   => '',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'dealership-has-been-activated' => [
                'variables'   => '{dealership_information}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'credit-fell-below-a-minimum'   => [
                'variables'   => '{user_min_credit},{user_credit},{user_credit_link}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 1,
                'admin-sms'   => 0,
            ],
            'contact-form-admin-reply'      => [
                'variables'   => '{visitor_name},{visitor_message},{signature},{admin_message},{message_send_date}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'message-from-admin'            => [
                'variables'   => '{signature},{admin_message}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'email-changed'                 => [
                'variables'   => '{browser},{platform},{ip},{location_country},{location_city},{date},{old_email},{new_email}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => [],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'password-changed'              => [
                'variables'   => '{browser},{platform},{ip},{location_country},{location_city},{date}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => [],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'failed-member-login-attempt'   => [
                'variables'   => '{browser},{platform},{ip},{location_country},{location_city},{date}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => [],
                'status'      => 1,
                'user-mail'   => 1,
                'admin-mail'  => 0,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
        ],
        'admin-messages' => [
            'contact-form'               => [
                'variables'   => '{user_full_name},{user_name},{user_surname},{user_email},{user_phone},{user_message}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4', '3', '2', '1'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'customer-feedback'          => [
                'variables'   => '{customer_full_name},{customer_name},{customer_surname},{customer_email},{customer_company_name},{customer_message}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'failed-order-activation'    => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link},{error_message}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'need-manually-upgrading'    => [
                'variables'   => '{product_old_name},{product_old_amount},{product_new_name},{product_new_amount},{difference_fee}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'need-manually-transaction'  => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link},{error_message},{reason}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'customer-has-upgraded'      => [
                'variables'   => '{product_old_name},{product_old_amount},{product_new_name},{product_new_amount},{difference_fee}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'cancel-request-created'     => [
                'variables'   => '{order_name},{order_amount},{order_date_created},{order_date_start},{order_date_end},{order_detail_link},{cancel_urgency},{cancel_reason}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => ['4'],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 1,
            ],
            'created-backup-db'          => [
                'variables'   => '',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => [],
                'status'      => 0,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
            'task-plan-created'          => [
                'variables'   => '{title},{description},{c_date},{due_date},{by_name},{admin_name},{departments},{detail_link}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => [],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 1,
            ],
            'reminding'                  => [
                'variables'   => '{note},{c_date},{reminder_time},{admin_name}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => [],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 1,
            ],
            'failed-admin-login-attempt' => [
                'variables'   => '{browser},{platform},{ip},{location_country},{location_city},{date}',
                'emails'      => NULL,
                'phones'      => NULL,
                'departments' => [],
                'status'      => 1,
                'user-mail'   => 0,
                'admin-mail'  => 1,
                'user-sms'    => 0,
                'admin-sms'   => 0,
            ],
        ],
    ],
];
