<?php 
return [
    'options' => [
        'ticket-assignable'             => true,
        'save-module-log'               => false,
        'blacklist'                     => [
            'status'                 => true,
            'use-producer-as-source' => true,
            'order-blocking'       => true,
            'risk-score'           => 5,
        ],
        'ctoc-service-transfer'         => [
            'status'                    => false,
            'domain'                    => [
                'status'                => false,
                'limit'                 => '',
            ],
            'hosting'                   => [
                'status'                => false,
                'limit'                 => '',
            ],
            'server'                    => [
                'status'                => false,
                'limit'                 => '',
            ],
            'software'                  => [
                'status'                => false,
                'limit'                 => '',
            ],
            'sms'                       => [
                'status'                => false,
                'limit'                 => '',
            ],
        ],
        'software-change-domain'        => [
            'status'                    => false,
            'limit'                     => '',
        ],
        'voice-notification'            => true,
        'proxy-block'                   => false,
        'location-verification'         => 0,
        'two-factor-verification'       => 0,
        'two-factor-verification-admin' => 0,
        'password-length'               => 5,
        'location-verification-type'    => 'country',
        'product-fields-extensions'     => '.jpg,.gif,.jpeg,.png,.doc,.xls,.pdf,.txt,.docx,.xlsx,.rar,.zip',
        'product-fields-max-file-size'  => 6291456,
        'attachment-extensions'         => '.jpg,.gif,.jpeg,.png,.doc,.xls,.pdf,.txt,.docx,.xlsx,.rar,.zip',
        'attachment-max-file-size'      => 2097152,
        'clear-end-two-zero-money'      => 1,
        'taxation'                      => 0,
        'taxation-type'                 => 'exclusive',
        'tax-rate'                      => 0,
        'country-tax-rates'             => [],
        'city-tax-rates'                => [],
        'use-coupon'                    => 1,
        'dealers-can-use-coupon'        => 1,
        'visitors-will-see-basket'      => 1,
        'crtacwshop'                    => 0,
        'client-index-show-products'    => 1,
        'cookie-policy'                 => [
            'status'            => 1,
            'page'              => 67,
        ],
        'redirect-https'                => 0,
        'redirect-www'                  => 0,
        'invoice-system'                => 1,
        'ticket-system'                 => 1,
        'kbase-system'                  => 1,
        'basket-system'                 => 1,
        'invoice-show-requires-login'   => 1,
        'delete-invoice-item-aoc'       => 1,
        'order-renewal-type'            => 'duedate',
        'detect-auto-price-on-invoice'  => 0,
        'international-sms-service'     => 1,
        'turkey-sms-service'            => 1,
        'sms-api-service'               => 1,
        'domain-profit-rate'            => 50,
        'product-upgrade'               => [
            'status'              => 1,
            'hosting'             => 1,
            'server'              => 1,
            'only-on-same-server' => 0,
        ],
        'send-bill-to-address'          => [
            'status' => 0,
            'amount' => 0,
            'cid'    => 0,
        ],
        'ns-addresses'                  => [
            'ns1' => 'ns1.example.com',
            'ns2' => 'ns2.example.com',
            'ns3' => '',
            'ns4' => '',
        ],
        'blocking-times'                => [
            'contact-form'      => [
                'hour' => 1,
            ],
            'create-ticket'     => [
                'minute' => 15,
            ],
            'reply-ticket'      => [
                'second' => 30,
            ],
            'customer-feedback' => [
                'day' => 1,
            ],
            'newsletter'        => [
                'day' => 1,
            ],
            'domain-check'      => [
                'hour' => 12,
            ],
            'forget-password'   => [
                'hour' => 3,
            ],
            'sign-in-attempt'   => [
                'hour' => 1,
            ],
            'email-verify'      => [
                'hour' => 1,
            ],
            'gsm-verify'        => [
                'hour' => 1,
            ],
        ],
        'cache-times'                   => [
            'slider'               => [
                'week' => 1,
            ],
            'sidebars'             => [
                'hour' => 12,
            ],
            'news-list'            => [
                'hour' => 1,
            ],
            'articles-list'        => [
                'hour' => 1,
            ],
            'references-list'      => [
                'hour' => 1,
            ],
            'knowledgebase-list'   => [
                'hour' => 1,
            ],
            'home-news-articles'   => [
                'day' => 1,
            ],
            'page-detail'          => [
                'day' => 1,
            ],
            'knowledgebase-detail' => [
                'hour' => 1,
            ],
            'category-detail'      => [
                'week' => 1,
            ],
            'cfeedbacks'           => [
                'day' => 1,
            ],
            'block-picture'        => [
                'day' => 1,
            ],
            'header-backgrounds'   => [
                'week' => 1,
            ],
        ],
        'contact-form'                  => 1,
        'contact-form-mandatory-phone'  => 1,
        'contact-map'                   => 1,
        'pagination-ranks'              => 10,
        'BotShield'                     => [
            'status'      => 1,
            'within-time' => [
                'minute' => 10,
            ],
            'attempts'    => [
                'contact'           => '10',
                'sign-up'           => '10',
                'sign-in'           => '10',
                'sign-forget'       => '10',
                'customer-feedback' => '2',
                'newsletter'        => '2',
                'domain-check'      => '100',
                'software-license'  => 2,
            ],
        ],
        'captcha'                       => [
            'status'            => 0,
            'software-license'  => 1,
            'contact-form'      => 1,
            'sign-up'           => 1,
            'sign-in'           => 1,
            'sign-forget'       => 1,
            'customer-feedback' => 1,
            'newsletter'        => 1,
            'domain-check'      => 1,
            'type'              => 'default',
            'default'           => false,
            'Google-reCaptcha'  => [
                'site-key'   => '',
                'secret-key' => '',
            ],
        ],
        'upload'                        => [
            'background-color' => '#eeeeee',
            'jpeg-quality'     => 100,
        ],
        'newsletters'                   => [
            'email' => 1,
        ],
        'sidebars'                      => [
            'page-detail-normal'     => 1,
            'page-detail-news'       => 1,
            'page-detail-articles'   => 1,
            'page-detail-references' => 1,
            'page-detail-kbase'      => 1,
            'news'                   => 1,
            'news-most-read'         => 1,
            'articles'               => 1,
            'articles-categories'    => 1,
            'articles-most-read'     => 1,
            'references'             => 1,
            'references-categories'  => 1,
            'references-most-read'   => 1,
        ],
        'limits'                        => [
            'news'                         => 4,
            'articles'                     => 4,
            'references'                   => 20,
            'sidebar-categories'           => 50,
            'sidebar-articles-most-read'   => 10,
            'sidebar-references-most-read' => 10,
            'sidebar-news-most-read'       => 10,
            'sidebar-normal-most-read'     => 10,
            'knowledgebase'                => 6,
            'softwares'                    => 6,
            'most-popular-softwares'       => 4,
            'most-popular-references'      => 4,
            'account-dashboard-news'       => 3,
            'account-dashboard-activity'   => 4,
            'account-tickets'              => 30,
            'account-messages'             => 30,
            'account-products'             => 30,
            'account-invoices'             => 30,
            'domain-box-tld'               => 7,
            'domain-home-tld'              => 7,
            'contact-form-sending'         => 99,
            'create-ticket-sending'        => 5,
            'customer-feedback-sending'    => 1,
            'newsletter-sending'           => 3,
            'domain-check'                 => 100,
        ],
        'domain-promotion-free'         => false,
        'domain-override-user-currency' => 0,
        'domain-whois-privacy'          => [
            'amount' => 1.0,
            'cid'    => 4,
        ],
        'panel-types'                   => ['cPanel', 'Plesk', 'DirectAdmin','CentosWebPanel'],
        'server-features'               => ['CloudLinux', 'LiteSpeed'],
        'product-types'                 => 'software,domain,hosting,server,sms,special',
        'pg-activation'                 => [
            'hosting'           => 1,
            'server'            => 1,
            'domain'            => 1,
            'software'          => 1,
            'sms'               => 1,
            'international-sms' => 1,
        ],
        'sign'                          => [
            'editable' => [
                'kind'           => true,
                'full_name'      => true,
                'email'          => false,
                'landline_phone' => false,
                'gsm'            => false,
                'identity'       => false,
                'birthday'       => false,
            ],
            'birthday' => [
                'status'   => 0,
                'required' => 0,
                'adult_verify' => 0,
            ],
            'forget'   => [
                'status'        => 1,
                'attempt_limit' => 1,
            ],
            'in'       => [
                'status'        => 1,
                'attempt_limit' => 10,
            ],
            'up'       => [
                'status'         => 1,
                'email'          => [
                    'verify'                => 0,
                    'verify_checking_limit' => 3,
                ],
                'gsm'            => [
                    'status'                => 1,
                    'required'              => 1,
                    'checker'               => 1,
                    'verify'                => 0,
                    'verify_checking_limit' => 3,
                ],
                'landline-phone' => [
                    'status'   => 0,
                    'required' => 0,
                    'checker'  => 0,
                ],
                'kind'           => [
                    'status'     => 1,
                    'individual' => [
                        'identity' => [
                            'status'   => 0,
                            'required' => 0,
                            'checker'  => 0,
                        ],
                    ],
                    'corporate'  => [
                        'company_name'       => [
                            'required' => 1,
                        ],
                        'company_tax_number' => [
                            'required' => 1,
                        ],
                        'company_tax_office' => [
                            'required' => 1,
                        ],
                    ],
                ],
            ],
            'security-question' => [
                'status' => 1,
                'required' => 0,
            ],
        ],
        'news-comment-embed-code'       => '',
        'blog-comment-embed-code'       => '',
        'hidsein'                       => false,
        'easy-order'                    => 1,
        'affiliate'                     => [
            'status'                        => false,
            'view-without-membership'       => false,
            'show-p-commission-rates'       => true,
            'commission-period'             => 'lifetime',
            'min-payment-amount'            => 10,
            'rate'                          => 10,
            'commission-delay'              => 7,
            'payment-gateways'              => [],
            'payment-gateways-lid'          => -1,
            'content'                       => [],
            'cookie-duration'               => 90,
        ],
        'dealership'                    => [
            'status'                        => true,
            'view-without-membership'       => true,
            'api'                           => false,
            'activation'                    => 'manuel',
            'rates'                         => [],
            'require_min_credit_amount'     => 0,
            'require_min_credit_cid'        => 4,
            'require_min_discount_amount'   => 0,
            'require_min_discount_cid'      => 0,
            'only_credit_paid'              => 0,
        ],
        'date-format'                   => "d/m/Y",
        'invoice-num-format'            => "{NUMBER}",
        'prohibited'                    => [],
    ],
];
