<?php 
return [
    'theme' => [
        'name'                 => 'Classic',
        'maintenance-mode'     => 0,
        'only-panel'           => 0,
        'favicon'              => 'resources/uploads/logo/favicon.ico',
        'clientArea-logo'      => 'resources/uploads/logo/clientArea.svg',
        'sign-logo'            => 'resources/uploads/logo/clientArea.svg',
        'header-logo'          => 'resources/uploads/logo/header.svg',
        'footer-logo'          => 'resources/uploads/logo/footer.svg',
        'notifi-header-logo'   => NULL,
        'notifi-footer-logo'   => NULL,
        'color1'               => '009595',
        'color2'               => '345a6c',
        'text-color'           => '607d8b',
        'meta-color'           => '#009595',
        'header-type'          => 1,
        'clientArea-type'      => 1,
        'slider'               => 1,
        'footlogos'            => 1,
        'breadcrumb-title'     => 85,
        'breadcrumb-addresses' => 140,
    ],
];
